### ISSUE TITLE
Parse is not called

### ISSUE THREAD

**Issue by rinatio** [PaulUithol/Backbone-relational#195]
After fetchRelated call model.parse method is not called, neither does collection.parse.

**Comment by flyingL123** [comment]
@PaulUithol can you elaborate on how that commit solves this issue? I'm trying to figure out how to accomplish the same thing. I have a `Rover.Models.Location` model with the following relation:
```
relations: [
    {
      type: 'HasMany',
      key: 'access_points',
      relatedModel: 'Rover.Models.AccessPoint',
      collectionType: 'Rover.Collections.AccessPoints',
      includeInJSON: 'id',
      reverseRelation: {
        key: 'location'
      }
    }
  ],
```
I need to `parse` the `Rover.Collections.AccessPoints` when it's created, but I can't seem to figure out a way to make that happen rather than doing it myself in the `Location` parse function. Is there any option I can pass to make this happen?
