### ISSUE TITLE
Nested model validation

### ISSUE THREAD

**Issue by safm** [PaulUithol/Backbone-relational#439]
Even when nested model's validation fails primary model's attributes are getting updated.
 
http://jsfiddle.net/sarfaraz/gnLmm/

**Comment by bpatram** [comment]
I understand this issue was opened 2 years ago but, based on your test case, your validation rules never caused any validation checks to fail. 
I have updated your test case here since the one you link to is broken: http://jsfiddle.net/jt6jLqh5/1/
When I write a validation rule that would cause it to fail the test still passes and the attribute is not set: http://jsfiddle.net/jt6jLqh5/2/
