### ISSUE TITLE
Fix for #407 breaks model saving with lazily loaded relations

### ISSUE THREAD

**Issue by Naddiseo** [PaulUithol/Backbone-relational#484]
The 'fix' for #407 breaks my code bad. I have a model with a HasOne relation to another model which is supposed to be lazily loaded, thus I only initially send down the id of the related model. I've also specified `includeInJSON` and so expect that when I call `save` that the id I specified is then sent back to the server indicating that the relation wasn't deleted. However, the field is being nullified which causes my code server side to think that the relation has been deleted.

```javascript

var M1 = Backbone.RelatedModel.extend({
    relations : [
        {
        type : Backbone.HasOne,
        key : 'other',
        relatedModel : 'M2',
        collectionType : 'M2Collection',
        createModels : false,
        includeInJSON : 'id'
        }
    ],
    attributes : {
        'other' : null
    },
    defaults : {
        'other' : null
    }
});

var m = new M1({ other : 1 });

m.save() // should send {other : 1} back to the server

```

**Comment by jeremymlane** [comment]
I don't think this is actually a bug. `{other : 1}` gets sent when I do this. The reason other still turns up null after saving is because `createModels: false`. When `createModels` is set to `true`, the relationship is updated correctly (or also if the an M2 model already exists with an id: 1. 

I'd recommend closing this one.
