### ISSUE TITLE
use backbone relational with other backbone plugins

### ISSUE THREAD

**Issue by elgubenis** [PaulUithol/Backbone-relational#506]
hi, i would like to know if you could explain me how to use Backbone.RelationalModel with another Backbone.Model-Plugin like Backbone.NestedModel ?

**Comment by philfreo** [comment]
Generally speaking, it's no problem to use Backbone-Relational with other Backbone plugins, as long as the core functionality doesn't conflict. However in the base of Backbone.NestedModel, it probably would, if you applied both plugins to the same model, since they inherently do different things.

If you think there's something specifically wrong here let us know and we can reopen.
