### ISSUE TITLE
Models without id (only cid) are not registered in Backbone.Relational.Store

### ISSUE THREAD

**Issue by mh-ovos** [PaulUithol/Backbone-relational#560]
Hello,
I see this is by design that models without id are not registered in Backbone.Relational.Store:
```javascript
					// Only register models that have an id. A model will be registered when/if it gets an id later on.
					if ( newId || newId === 0 ) {
						Backbone.Relational.store.register( this );
					}
```

Can you explain why is it so? Would it be bad if all models (also without id) are registered in the store? I have a situation in which I have some "temporary" models, without ids, but I want them to be kept in the store for some time and look them up by cid later.

**Comment by bpatram** [comment]
When calling `findOrCreate` on a model while defining the id (`model.findOrCreate({ id: 1, ... }`); it will look up into the store to find that model instance with that `id` and then update it with the additional attributes you are setting and return itself. That logic is determined by the `find` method on [`Backbone.Relational.store`](https://github.com/PaulUithol/Backbone-relational/blob/master/backbone-relational.js#L432) which is called by that model's [`findModel`](https://github.com/PaulUithol/Backbone-relational/blob/master/backbone-relational.js#L1879) method.

It wouldn't make sense if, when looking into the store to resolve models, for it to find models without an `id`. That would break the functionality of `findOrCreate` since it would never create a new model instance but rather always resolve to the one model without an `id` by default.

---
If you need to keep temporary models in the store then you could generate a temporary `id` for them using something like `new Model({ id: _.uniqueId('temp') })`.
