### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by bpatram** [PaulUithol/Backbone-relational#562]
The last commit was from September 2015, 5 months ago. There are stacks of issues and pull requests left opened. 

@PaulUithol can you make a short statement regarding this project and its future? Are you looking for new maintainers?

**Comment by PaulUithol** [comment]
Hi,

Yes, I've been planning to do that for a while now. Sorry that it kept
slipping my mind. Since I have been in a completely different business for
a while now that's completely absorbing, I am looking for other people to
help maintain. I'll probably be doing more in again software at some point,
but at this moment I'm running cartographic/osm/open data projects in
Tanzania and rural Uganda ;).

So I do want to give a few that are motivated commit rights. Have been
wanting to open a separate issue for that. But if it's something you (or
anyone else) would like to do, please let me know!

**Comment by bpatram** [comment]
I'll gladly take over this project and keep it going. We use this library extensively for a lot of proprietary/client projects in house and I would hate to see it fade away. We've invested a lot of time extending this library and I hope to keep this working with the most recent versions of Backbone. Let me know how you wish to proceed!

**Comment by PaulUithol** [comment]
Hi Brandon, thanks for the offer. Let me add you as a contributor first - that should allow you to work on issues, do commits, etc. And we'll see how to proceed from there!

**Comment by flowhamster** [comment]
@bpatram are you looking for help?

I've made some local modifications to make the library es6 compatible. It would be awesome to keep this up to date since its one of the better libraries I've used.

**Comment by bpatram** [comment]
@flowhamster Absolutely! Feel free to send in a PR. I just recently setup TravisCI and moved the unit tests so you may want to merge master into your branch and make re-run any unit tests or update them to pass!

**Comment by ryan-farmer** [comment]
For what it's worth, I used BBR at a prior job and am investigating it for a current project for a large-ish scale BB/Marionette application. Would love to see this project get continued maintenance.
